version: "3"
services:
  gateway:
    image: nginx
    environment:
      - USERSVC_ADDR=usersvc:5000
      - LIBRARYSVC_ADDR=librarysvc:5000
      - SHOPESVC_ADDR=shopesvc:5000
      - CATALOGUESVC_ADDR=cataloguesvc:5000
    volumes:
      - ./nginx:/etc/nginx/conf.d
    #command: /bin/bash "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8080:80
  usersvc:
    build: ./userapi
    environment:
      - FLASK_SERVER_PORT=5000
      - FLASK_ENV=development
    ports:
      - 5001:5000
    volumes:
      - ./userapi:/app
    depends_on:
      - gateway
  librarysvc:
    build: ./libraryapi
    environment:
      - FLASK_SERVER_PORT=5000
      - FLASK_ENV=development
    ports:
      - 5002:5000
    volumes:
      - ./libraryapi:/app
    depends_on:
      - gateway
  shopesvc:
    build: ./shopeapi
    environment:
      - FLASH_SERVER_PORT=5000
      - FLASK_ENV=development
    ports:
      - 5003:5000
    volumes:
      - ./shopeapi:/app
    depends_on:
      - gateway
  cataloguesvc:
    build: ./catalogueapi
    environment:
      - FLASH_SERVER_POST=5000
      - FLASK_ENV=development
    ports:
      - 5004:5000
    volumes:
      - ./catalogueapi:/app
